owner              = "faisal"
aws_region         = "us-east-1"
repo               = "faisalcodesinfrastructure/packer-cis-amazon-linux-2-level-2"
bucket_name        = "cis-amazon-linux-2"
bucket_description = "Image based on CIS Amazon Linux 2 Benchmark - Paid for by Mr. Norris"
aws_instance_type  = "c3.large"