---
- name: Provision Base Image
  hosts: default
  become: true

  tasks:
# System Activity Reporter Tool
    - name: Install Sar
      package:
        name: 'sar'
        state: present
 
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest