---
- name: Provision image
  hosts: default
  become: true
  
  tasks:
    - name: Install Tomcat
      package:
        name: 'tomcat'
        state: present

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
